---

- hosts: all
  become: true
  vars_files:
    - vars.yml

  tasks:

  - name: Get the platform (i386 or amd64) of the virtual machine
    command: dpkg --print-architecture
    register: print_architecture

  - name: And set the actual platform value as a variable
    set_fact:
      platform: "{{ print_architecture.stdout }}"

  - name: Update and upgrade apt packages
    apt:
      upgrade: safe
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: Install packages for orchardcore and ansible (SLOW)
    apt:
      pkg:
      - unzip
      - vim
      - curl
      - expect
      - python-pexpect
      - python-pip
      - docker.io
      - git

  - name: Make sure docker autostarts and is started
    service: name=docker enabled=yes state=started

  - name: Install docker for python to handle docker from ansible
    pip: 
      name:
        - docker
        - jsondiff

  - name: Copy the docker-compose file
    template:
      src: /orchardcore/docker-compose.yml
      dest: /usr/local

  - name: Set db password
    lineinfile:
      path: /usr/local/docker-compose.yml
      regexp: 'POSTGRES_PASSWORD: example'
      line: '      POSTGRES_PASSWORD: {{ postgrespassword }}'

  - name: Initialize a new swarm with default parameters
    docker_swarm:
      state: present

  - name: Deploy orchardcore docker stack
    docker_stack:
      state: present
      name: orchardcore
      compose:
        - /usr/local/docker-compose.yml

  - name: Wait for orchardcore stack to start
    wait_for:
      port: 80
      delay: 5

